# finetuning/sweep_config.yaml

# A descriptive name for this experiment. A directory with this name will be created.
experiment_name: "qwen1.7B_binary_tasks_paper_replication"

# The root directory where all experiment results will be saved.
results_root: "./finetuning/results_new"

# --------------------------------------------------------------------------------
# Base arguments that are FIXED for all runs in this sweep.
# These are the default command-line arguments for main.py.
# --------------------------------------------------------------------------------
base_args:
  model: "qwen1.7B"
  train_set_size: 200
  test_set_size: 10000
  batch_size: 20
  lr: 1e-5
  eta_min: 1e-6
  n_epochs: 200
  weight_decay: 1e-5
  precision: "bf16"
  device: "cuda"
  seed: 42

# --------------------------------------------------------------------------------
# The grid of hyperparameters to VARY.
# The script will generate a run for every possible combination of these values.
# Total runs = len(sequence_length) * len(target_func) = 5 * 4 = 20 runs.
# --------------------------------------------------------------------------------
grid:
  sequence_length:
    - 100
    - 50
    - 30
    - 25
    - 20
  
  target_func: # Using our new, unified function names!
    - "fn_g"  # palindrome
    - "fn_a"  # parity_all
    - "fn_d"  # patternmatch2 ('00111111')
    - "fn_c"  # patternmatch1 ('10101010')
    # Add other functions from the paper replication here...